import pyautogui
import time
import pyperclip
pyautogui.press('win')
time.sleep(2)
pyautogui.write('chrome')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.hotkey("ctrl","t")
time.sleep(2)
pyperclip.copy("https://github.com/gbborigens")
time.sleep(2)
pyautogui.hotkey('ctrl','v')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.hotkey("ctrl","g")
time.sleep(2)
pyautogui.write("button")
time.sleep(2)
pyautogui.press('esc')
pyautogui.press('esc')
time.sleep(1)
pyautogui.hotkey('ctrl','l')
time.sleep(2)
pyperclip.copy('https://github.com/gbborigens/button')
time.sleep(2)
pyautogui.hotkey('ctrl','v')
pyautogui.press('enter')
time.sleep(2)
pyautogui.hotkey("ctrl","g")
time.sleep(1)
pyautogui.write('Arithmetics colors')
time.sleep(1)
pyautogui.press('esc')
pyautogui.press('esc')
time.sleep(1)
pyautogui.hotkey('ctrl','l')
time.sleep(2)
pyperclip.copy('https://github.com/gbborigens/button/blob/main/Arithmetics%20colors.html')
time.sleep(2)
pyautogui.hotkey('ctrl','v')
pyautogui.press('enter')